name: "Display Python Version"

on: push

jobs:
  setuppython:
    name: Setup Python
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.10.12"
      - run: python --version

  pyversion:
    name: "Display Python version now"
    runs-on: ubuntu-latest
    steps:
      - run: python --version


