name: "Test the code"

on:
  push:
    branches:
      - main

jobs:
  codetest:
    name: Code test runner
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.10.12"
      - run: pytest
      - run: python -m pip install -r requirements.txt
      - run: pytest

